import React, { useState } from 'react';
import { calculateAiCosts } from '../utils/tokenEngine';
import { Sparkles, Download, Code, Heart } from 'lucide-react';
import { getTranslation } from '../i18n';

export default function DevTokenCalculator({ lang = 'en' }) {
  const t = (path) => getTranslation(lang, path);

  const [inputMTokens, setInputMTokens] = useState(10); // 10 Million Tokens
  const [outputMTokens, setOutputMTokens] = useState(5);  // 5 Million Tokens
  const [showEmbed, setShowEmbed] = useState(false);

  const results = calculateAiCosts(inputMTokens, outputMTokens);

  const handleExportReport = () => {
    let reportText = `
--------------------------------------------------
LLM API MODEL COST REPORT
Generated by GlobalPayCalc.com (Universal Utility Engine)
--------------------------------------------------
Monthly Input Tokens: ${inputMTokens}M Tokens
Monthly Output Tokens: ${outputMTokens}M Tokens

PROJECTIONS:
`;

    results.forEach(model => {
      reportText += `\n- ${model.name} (${model.provider}): Monthly: $${model.monthlyTotal.toFixed(2)} USD / Yearly: $${model.yearlyTotal.toFixed(0)} USD`;
    });

    reportText += `

--------------------------------------------------
VERIFIED LINK: https://globalpaycalc.com
Powered by GlobalPayCalc.com - 100% Free & Client-Side
--------------------------------------------------
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([reportText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `GlobalPayCalc_AI_Token_Report.txt`;
    document.body.appendChild(element);
    element.click();
    element.remove();
  };

  const embedCode = `<iframe src="https://globalpaycalc.com" width="100%" height="750" style="border:1px solid #1e293b; border-radius:16px;" title="AI Model API Token Cost Calculator"></iframe><p style="font-size:11px; text-align:center;">Powered by <a href="https://globalpaycalc.com" target="_blank" rel="dofollow">GlobalPayCalc.com</a></p>`;

  return (
    <div className="space-y-8">
      {/* Component Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-semibold">
          <Sparkles className="w-3.5 h-3.5" />
          <span>{t('ai.title')}</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          {t('ai.title')}
        </h2>
        <p className="text-slate-400 text-sm leading-relaxed">
          {t('ai.subtitle')}
        </p>
      </div>

      {/* Controls Card */}
      <div className="glass-card p-6 sm:p-8 rounded-2xl max-w-4xl mx-auto space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Input Tokens Slider */}
          <div className="space-y-2">
            <div className="flex justify-between items-center text-xs font-semibold">
              <label className="text-slate-300">{t('ai.input')} (Millions)</label>
              <span className="text-purple-400 font-mono text-base font-bold">{inputMTokens}M Tokens</span>
            </div>
            <input
              type="range"
              min="1"
              max="200"
              step="1"
              value={inputMTokens}
              onChange={(e) => setInputMTokens(Number(e.target.value))}
              className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-purple-500"
            />
            <div className="flex justify-between text-[10px] text-slate-500 font-mono">
              <span>1M</span>
              <span>100M</span>
              <span>200M</span>
            </div>
          </div>

          {/* Output Tokens Slider */}
          <div className="space-y-2">
            <div className="flex justify-between items-center text-xs font-semibold">
              <label className="text-slate-300">{t('ai.output')} (Millions)</label>
              <span className="text-brand-400 font-mono text-base font-bold">{outputMTokens}M Tokens</span>
            </div>
            <input
              type="range"
              min="1"
              max="100"
              step="1"
              value={outputMTokens}
              onChange={(e) => setOutputMTokens(Number(e.target.value))}
              className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-brand-500"
            />
            <div className="flex justify-between text-[10px] text-slate-500 font-mono">
              <span>1M</span>
              <span>50M</span>
              <span>100M</span>
            </div>
          </div>

        </div>

        {/* Buttons for Share / Embed */}
        <div className="pt-2 flex flex-col sm:flex-row gap-2 max-w-lg mx-auto">
          <button
            onClick={handleExportReport}
            className="flex-1 py-3 px-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition flex items-center justify-center space-x-2 cursor-pointer border border-slate-700"
          >
            <Download className="w-4 h-4 text-emerald-400" />
            <span>{t('ai.downloadReport')}</span>
          </button>
          <button
            onClick={() => setShowEmbed(!showEmbed)}
            className="py-3 px-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition flex items-center justify-center space-x-2 cursor-pointer border border-slate-700"
          >
            <Code className="w-4 h-4 text-brand-400" />
            <span>{t('ai.embed')}</span>
          </button>
        </div>

        {/* Embed Code Panel */}
        {showEmbed && (
          <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
            <span className="text-[10px] text-slate-400 font-semibold block">{t('ai.embedLabel')}</span>
            <textarea
              readOnly
              value={embedCode}
              onClick={(e) => e.target.select()}
              className="w-full h-20 bg-slate-900 border border-slate-800 rounded-lg p-2 text-[10px] font-mono text-slate-300 focus:outline-none cursor-pointer"
            />
            <span className="text-[9px] text-slate-500">{t('ai.embedNotice')}</span>
          </div>
        )}
      </div>

      {/* Model Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
        {results.map((model) => (
          <div key={model.id} className="glass-card glass-card-hover p-6 rounded-2xl flex flex-col justify-between space-y-4">
            <div>
              <div className="flex justify-between items-center mb-3">
                <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider">{model.provider}</span>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-brand-500/10 text-brand-400 border border-brand-500/20">
                  {model.badge}
                </span>
              </div>
              <h3 className="text-lg font-bold text-white mb-2">{model.name}</h3>
              <div className="text-xs text-slate-400 font-mono">Context: {model.contextWindow}</div>
            </div>

            <div className="space-y-2 py-3 border-t border-b border-slate-800/80">
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">{t('ai.inputCost')}</span>
                <span className="text-slate-200 font-mono">${model.inputTotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-xs">
                <span className="text-slate-400">{t('ai.outputCost')}</span>
                <span className="text-slate-200 font-mono">${model.outputTotal.toFixed(2)}</span>
              </div>
            </div>

            <div>
              <div className="text-xs text-slate-400">{t('ai.monthly')}</div>
              <div className="text-2xl font-extrabold text-emerald-400 font-mono">
                ${model.monthlyTotal.toFixed(2)}
              </div>
              <div className="text-[11px] text-slate-500 mt-0.5">{t('ai.yearly')}: ${model.yearlyTotal.toFixed(0)}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Recommendations */}
      <div className="glass-card p-6 rounded-2xl border-slate-800 space-y-4 max-w-4xl mx-auto">
        <h4 className="text-xs font-bold text-white flex items-center space-x-2 uppercase tracking-wide">
          <Heart className="w-4 h-4 text-purple-500" />
          <span>{t('ai.recommendedAi')}</span>
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
          <a
            href="https://aws.amazon.com/free/?utm_source=globalpaycalc"
            target="_blank"
            rel="noopener noreferrer"
            className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
          >
            <div>
              <div className="font-bold text-white">{t('ai.aws')}</div>
              <p className="text-[10px] text-slate-400 mt-1">{t('ai.awsDesc')}</p>
            </div>
            <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('ai.awsCta')}</span>
          </a>

          <a
            href="https://platform.openai.com/signup?utm_source=globalpaycalc"
            target="_blank"
            rel="noopener noreferrer"
            className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
          >
            <div>
              <div className="font-bold text-white">{t('ai.openAi')}</div>
              <p className="text-[10px] text-slate-400 mt-1">{t('ai.openAiDesc')}</p>
            </div>
            <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('ai.openAiCta')}</span>
          </a>

          <a
            href="https://console.anthropic.com/signup?utm_source=globalpaycalc"
            target="_blank"
            rel="noopener noreferrer"
            className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
          >
            <div>
              <div className="font-bold text-white">{t('ai.anthropic')}</div>
              <p className="text-[10px] text-slate-400 mt-1">{t('ai.anthropicDesc')}</p>
            </div>
            <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('ai.anthropicCta')}</span>
          </a>
        </div>
      </div>

    </div>
  );
}
