import React, { useState } from 'react';
import { calculateGlobalTakeHome, globalTaxCountries } from '../utils/globalTakeHomeEngine';
import { DollarSign, ShieldCheck, PieChart, Info, Download, Code, Globe } from 'lucide-react';
import { getTranslation } from '../i18n';

export default function GlobalTakeHomeCalculator({ lang = 'en' }) {
  const t = (path) => getTranslation(lang, path);

  const [grossAmount, setGrossAmount] = useState(90000);
  const [selectedCountry, setSelectedCountry] = useState('US_CA');
  const [period, setPeriod] = useState('annual');

  const result = calculateGlobalTakeHome(grossAmount, selectedCountry, period);

  const handleExportReport = () => {
    const reportText = `
--------------------------------------------------
GLOBAL NET TAKE-HOME PAY REPORT
Generated by GlobalPayCalc.com (Universal Utility Engine)
--------------------------------------------------
Country: ${result.country.flag} ${result.country.name}
Gross Salary (${period}): ${result.country.symbol}${grossAmount.toLocaleString()} ${result.country.currency}
Gross Annual: ${result.country.symbol}${Math.round(result.grossAnnual).toLocaleString()} ${result.country.currency}

Deductions Breakdown:
${result.deductionsDetails.map(d => `- ${d.name}: ${result.country.symbol}${Math.round(d.amount).toLocaleString()}`).join('\n')}

Total Deductions: ${result.country.symbol}${Math.round(result.totalDeductions).toLocaleString()} (Effective Tax: ${result.effectiveTaxRate}%)
NET ANNUAL TAKE-HOME: ${result.country.symbol}${Math.round(result.netAnnual).toLocaleString()} ${result.country.currency}
NET MONTHLY TAKE-HOME: ${result.country.symbol}${Math.round(result.netMonthly).toLocaleString()} ${result.country.currency}

--------------------------------------------------
VERIFIED LINK: https://globalpaycalc.com/take-home
Powered by GlobalPayCalc.com - 100% Free & Client-Side
--------------------------------------------------
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([reportText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `TakeHome_Report_${selectedCountry}.txt`;
    document.body.appendChild(element);
    element.click();
    element.remove();
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Component Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-semibold">
          <Globe className="w-3.5 h-3.5" />
          <span>Dinamik Ülke Bazlı Vergi Motoru</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          Global Net Maaş ve Vergi Hesaplayıcı
        </h2>
        <p className="text-slate-400 text-sm leading-relaxed">
          ABD (Federal + Eyalet + FICA), İngiltere, Almanya, Türkiye ve 40+ ülkenin güncel vergi ve sosyal güvenlik kesintilerini hesaplayın.
        </p>
      </div>

      {/* Main Glass Card Form */}
      <div className="glass-card p-6 sm:p-8 rounded-3xl border-slate-800 space-y-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Amount Input */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center space-x-1">
              <DollarSign className="w-3.5 h-3.5 text-brand-400" />
              <span>Brüt Maaş Tutarı ({result.country.currency})</span>
            </label>
            <input 
              type="number" 
              value={grossAmount} 
              onChange={(e) => setGrossAmount(Number(e.target.value))} 
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-lg focus:outline-none focus:border-brand-500 transition"
              placeholder="90000"
            />
          </div>

          {/* Period Selector */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              Maaş Dönemi
            </label>
            <select
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-base focus:outline-none focus:border-brand-500 transition cursor-pointer"
            >
              <option value="annual">Yıllık Brüt</option>
              <option value="monthly">Aylık Brüt</option>
            </select>
          </div>

          {/* Country Selector */}
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              Ülke / Eyalet Mevzuatı
            </label>
            <select
              value={selectedCountry}
              onChange={(e) => setSelectedCountry(e.target.value)}
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-base focus:outline-none focus:border-brand-500 transition cursor-pointer"
            >
              {Object.values(globalTaxCountries).map(c => (
                <option key={c.id} value={c.id}>
                  {c.flag} {c.name} ({c.currency})
                </option>
              ))}
            </select>
          </div>

        </div>

        {/* Results Overview */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-4">
          <div className="bg-slate-900/80 border border-slate-800 p-6 rounded-2xl space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Aylık Ele Geçen Net</span>
            <div className="text-3xl font-black text-emerald-400">
              {result.country.symbol}{Math.round(result.netMonthly).toLocaleString()} <span className="text-xs font-normal text-slate-400">/ ay</span>
            </div>
            <p className="text-[11px] text-slate-400">Vergi ve sigorta kesintileri düşüldükten sonra net tutar.</p>
          </div>

          <div className="bg-slate-900/80 border border-slate-800 p-6 rounded-2xl space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Yıllık Ele Geçen Net</span>
            <div className="text-3xl font-black text-white">
              {result.country.symbol}{Math.round(result.netAnnual).toLocaleString()}
            </div>
            <p className="text-[11px] text-slate-400">Yıllık toplam harcanabilir net bütçeniz.</p>
          </div>

          <div className="bg-slate-900/80 border border-slate-800 p-6 rounded-2xl space-y-2">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Efektif Vergi Oranı</span>
            <div className="text-3xl font-black text-rose-400">
              %{result.effectiveTaxRate}
            </div>
            <p className="text-[11px] text-slate-400">Brüt gelirden yapılan toplam yasal kesinti oranı.</p>
          </div>
        </div>

        {/* Deductions Breakdown Table */}
        <div className="space-y-4 pt-4 border-t border-slate-800">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-white flex items-center space-x-2">
              <PieChart className="w-4 h-4 text-brand-400" />
              <span>Yasal Kesinti ve Vergi Detayları ({result.country.name})</span>
            </h3>
            <button 
              onClick={handleExportReport}
              className="px-3 py-1.5 rounded-lg bg-brand-500/10 border border-brand-500/20 text-brand-300 hover:bg-brand-500/20 text-xs font-bold transition flex items-center space-x-1.5"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Raporu İndir (.txt)</span>
            </button>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-800 text-xs font-bold text-slate-400 uppercase">
                  <th className="py-3 px-4">Kesinti Kalemi</th>
                  <th className="py-3 px-4 text-right">Yıllık Tutar</th>
                  <th className="py-3 px-4 text-right">Oran</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/50 text-sm">
                {result.deductionsDetails.map((d, idx) => (
                  <tr key={idx} className="hover:bg-slate-800/20 transition">
                    <td className="py-3 px-4 font-semibold text-slate-200">{d.name}</td>
                    <td className="py-3 px-4 text-right font-mono text-rose-300">
                      -{result.country.symbol}{Math.round(d.amount).toLocaleString()}
                    </td>
                    <td className="py-3 px-4 text-right font-mono text-slate-400">
                      %{result.grossAnnual > 0 ? ((d.amount / result.grossAnnual) * 100).toFixed(1) : 0}
                    </td>
                  </tr>
                ))}
                <tr className="bg-slate-900/50 font-bold border-t border-slate-700">
                  <td className="py-3 px-4 text-white">Toplam Yasal Kesintiler</td>
                  <td className="py-3 px-4 text-right text-rose-400 font-mono">
                    -{result.country.symbol}{Math.round(result.totalDeductions).toLocaleString()}
                  </td>
                  <td className="py-3 px-4 text-right text-rose-400 font-mono">
                    %{result.effectiveTaxRate}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
}
