import React, { useState } from 'react';
import { calculateGlobalInvoice, countryVatRates } from '../utils/vatTaxEngine';
import { FileText, Copy, Info } from 'lucide-react';
import calcTranslations from '../data/calculatorTranslations';

export default function GlobalInvoiceVatCalculator({ lang = 'en' }) {
  const [amount, setAmount] = useState(2500);
  const [selectedCountry, setSelectedCountry] = useState('DE');
  const [calculationType, setCalculationType] = useState('netToGross');
  const [isB2B, setIsB2B] = useState(true);
  const [isCrossBorderReverseCharge, setIsCrossBorderReverseCharge] = useState(true);
  const [copied, setCopied] = useState(false);

  const tCalc = calcTranslations[lang] || calcTranslations['en'];
  const result = calculateGlobalInvoice({
    amount,
    countryKey: selectedCountry,
    calculationType,
    isB2B,
    isCrossBorderReverseCharge
  });

  const handleCopyBreakdown = () => {
    const text = `
INVOICE TAX BREAKDOWN
--------------------------------------------------
Country Jurisdiction: ${result.country.flag} ${result.country.name}
Invoice Type: ${isB2B ? 'B2B Cross-Border Service' : 'B2C Local Service'}
Net Subtotal: $${result.netAmount.toLocaleString()} USD
VAT / Tax Rate: ${result.effectiveVatRatePercent}%
VAT / Tax Amount: $${result.vatAmount.toLocaleString()} USD
GROSS TOTAL INVOICE: $${result.grossAmount.toLocaleString()} USD

Notes: ${result.invoiceNote}
--------------------------------------------------
Generated by GlobalPayCalc.com (Universal Utility Engine)
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Component Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-semibold">
          <FileText className="w-3.5 h-3.5" />
          <span>{tCalc.vatBadge}</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          {tCalc.vatTitle}
        </h2>
        <p className="text-slate-400 text-sm leading-relaxed">
          {tCalc.vatDesc}
        </p>
      </div>

      {/* Main Glass Form */}
      <div className="glass-card p-6 sm:p-8 rounded-3xl border-slate-800 space-y-8">
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              {lang === 'tr' ? 'Tutar ($ / € / ₺)' : 'Amount ($ / € / ₺)'}
            </label>
            <input 
              type="number" 
              value={amount} 
              onChange={(e) => setAmount(Number(e.target.value))} 
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-lg focus:border-purple-500 outline-none"
              placeholder="2500"
            />
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              {tCalc.transactionTypeLabel}
            </label>
            <select
              value={calculationType}
              aria-label="Transaction VAT Calculation Direction"
              onChange={(e) => setCalculationType(e.target.value)}
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-base focus:border-purple-500 outline-none cursor-pointer"
            >
              <option value="netToGross">
                {lang === 'tr' ? "KDV'siz Tutar ➔ KDV Dahil (Net'ten Brüt'e)" : "Net Amount ➔ VAT Included (Net to Gross)"}
              </option>
              <option value="grossToNet">
                {lang === 'tr' ? "KDV Dahil Tutar ➔ KDV Hariç (Brüt'ten Net'e)" : "VAT Included ➔ VAT Excluded (Gross to Net)"}
              </option>
            </select>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-300 uppercase tracking-wider">
              {lang === 'tr' ? 'Hedef Ülke / Vergi Rejimi' : 'Target Country / Tax Regime'}
            </label>
            <select
              value={selectedCountry}
              aria-label="Target Country VAT Regime"
              onChange={(e) => setSelectedCountry(e.target.value)}
              className="w-full bg-slate-900 border border-slate-800 rounded-xl px-4 py-3 text-white font-bold text-base focus:border-purple-500 outline-none cursor-pointer"
            >
              {Object.entries(countryVatRates).map(([code, c]) => (
                <option key={code} value={code}>
                  {c.flag} {c.name} (%{c.standardVat})
                </option>
              ))}
            </select>
          </div>

        </div>

        {/* Checkbox Options */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-900/60 p-4 rounded-2xl border border-slate-800">
          <label className="flex items-center space-x-3 cursor-pointer">
            <input 
              type="checkbox" 
              checked={isB2B} 
              onChange={(e) => setIsB2B(e.target.checked)} 
              className="w-4 h-4 rounded border-slate-700 text-purple-600 focus:ring-purple-500 bg-slate-950"
            />
            <span className="text-sm font-semibold text-slate-200">
              {lang === 'tr' ? 'B2B Kurumsal Müşteri Faturası' : 'B2B Corporate Client Invoice'}
            </span>
          </label>

          <label className="flex items-center space-x-3 cursor-pointer">
            <input 
              type="checkbox" 
              checked={isCrossBorderReverseCharge} 
              onChange={(e) => setIsCrossBorderReverseCharge(e.target.checked)} 
              className="w-4 h-4 rounded border-slate-700 text-purple-600 focus:ring-purple-500 bg-slate-950"
            />
            <span className="text-sm font-semibold text-slate-200">
              {tCalc.reverseChargeLabel}
            </span>
          </label>
        </div>

        {/* Invoice Summary Output */}
        <div className="bg-slate-900/90 border border-slate-800 p-6 rounded-2xl space-y-6">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-white flex items-center space-x-2">
              <FileText className="w-4 h-4 text-purple-400" />
              <span>{tCalc.invoiceResults}</span>
            </h3>
            <button 
              onClick={handleCopyBreakdown}
              className="px-3 py-1.5 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-300 hover:bg-purple-500/20 text-xs font-bold transition flex items-center space-x-1.5"
            >
              <span>{copied ? (lang === 'tr' ? 'Kopyalandı! ✅' : 'Copied! ✅') : (lang === 'tr' ? 'Kopyala' : 'Copy')}</span>
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-slate-950/80 p-5 rounded-xl border border-slate-800">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{tCalc.netBasePrice}</span>
              <div className="text-2xl font-black text-white mt-1">
                ${result.netAmount.toLocaleString()}
              </div>
            </div>

            <div className="bg-slate-950/80 p-5 rounded-xl border border-slate-800">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                {tCalc.calculatedVat} ({result.effectiveVatRatePercent}%)
              </span>
              <div className="text-2xl font-black text-purple-400 mt-1">
                ${result.vatAmount.toLocaleString()}
              </div>
            </div>

            <div className="bg-slate-950/80 p-5 rounded-xl border border-slate-800">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">{tCalc.grossInvoiceTotal}</span>
              <div className="text-2xl font-black text-emerald-400 mt-1">
                ${result.grossAmount.toLocaleString()}
              </div>
            </div>
          </div>

          {/* Legal Invoice Note */}
          <div className="bg-purple-950/20 border border-purple-500/20 p-4 rounded-xl text-xs text-purple-300 flex items-start space-x-2">
            <Info className="w-4 h-4 shrink-0 mt-0.5" />
            <span><strong>{lang === 'tr' ? 'Fatura Notu' : 'Invoice Note'}:</strong> {result.invoiceNote}</span>
          </div>
        </div>

      </div>
    </div>
  );
}
