import React, { useState } from 'react';
import { calculateNomadTaxParity, countryTaxData } from '../utils/taxEngine';
import { Globe, TrendingUp, DollarSign, Download, Code, ShieldCheck, Heart } from 'lucide-react';
import { getTranslation } from '../i18n';

export default function NomadTaxCalculator({ lang = 'en' }) {
  const t = (path) => getTranslation(lang, path);

  const [grossSalary, setGrossSalary] = useState(85000);
  const [homeCountry, setHomeCountry] = useState('US_CA');
  const [targetCountry, setTargetCountry] = useState('ES');
  const [showEmbed, setShowEmbed] = useState(false);

  const result = calculateNomadTaxParity(grossSalary, homeCountry, targetCountry);

  const handleExportReport = () => {
    const reportText = `
--------------------------------------------------
GLOBAL REMOTE TAX PARITY REPORT
Generated by GlobalPayCalc.com (Universal Utility Engine)
--------------------------------------------------
Gross Salary: $${grossSalary.toLocaleString()} USD
Origin: ${result.home.flag} ${result.home.name} (Effective Tax: ${(result.home.effTax * 100)}%)
Destination: ${result.target.flag} ${result.target.name} (Effective Tax: ${(result.target.effTax * 100)}%)

Net Monthly (Origin): $${Math.round(result.home.netMonthly).toLocaleString()} USD
Net Monthly (Destination): $${Math.round(result.target.netMonthly).toLocaleString()} USD
Purchasing Power Index: ${result.purchasingPowerBoost}x
Equivalent Living Standard in Target: $${Math.round(result.equivalentNetMonthly).toLocaleString()}/mo

--------------------------------------------------
VERIFIED LINK: https://globalpaycalc.com
Powered by GlobalPayCalc.com - 100% Free & Client-Side
--------------------------------------------------
    `.trim();

    const element = document.createElement("a");
    const file = new Blob([reportText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `GlobalPayCalc_Tax_Report_${homeCountry}_to_${targetCountry}.txt`;
    document.body.appendChild(element);
    element.click();
    element.remove();
  };

  const embedCode = `<iframe src="https://globalpaycalc.com" width="100%" height="700" style="border:1px solid #1e293b; border-radius:16px;" title="Remote Salary Parity Calculator"></iframe><p style="font-size:11px; text-align:center;">Powered by <a href="https://globalpaycalc.com" target="_blank" rel="dofollow">GlobalPayCalc.com</a></p>`;

  return (
    <div className="space-y-8">
      {/* Component Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-brand-500/10 border border-brand-500/20 text-brand-400 text-xs font-semibold">
          <Globe className="w-3.5 h-3.5" />
          <span>{t('salary.title')}</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
          {t('salary.title')}
        </h2>
        <p className="text-slate-400 text-sm leading-relaxed">
          {t('salary.subtitle')}
        </p>
      </div>

      {/* Calculator Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Controls Card */}
        <div className="lg:col-span-5 glass-card p-6 sm:p-8 rounded-2xl space-y-6">
          <h3 className="text-lg font-bold text-white flex items-center space-x-2">
            <DollarSign className="w-5 h-5 text-brand-400" />
            <span>{t('salary.gross')}</span>
          </h3>

          {/* Gross Salary Slider */}
          <div className="space-y-2">
            <div className="flex justify-between items-center text-xs font-semibold">
              <label className="text-slate-300">{t('salary.gross')} (USD)</label>
              <span className="text-brand-400 font-mono text-base font-bold">${grossSalary.toLocaleString()}</span>
            </div>
            <input
              type="range"
              min="20000"
              max="350000"
              step="5000"
              value={grossSalary}
              onChange={(e) => setGrossSalary(Number(e.target.value))}
              className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-brand-500"
            />
            <div className="flex justify-between text-[10px] text-slate-500 font-mono">
              <span>$20,000</span>
              <span>$180,000</span>
              <span>$350,000</span>
            </div>
          </div>

          {/* Home Country Selector */}
          <div className="space-y-2">
            <label className="block text-xs font-semibold text-slate-300">{t('salary.home')}</label>
            <select
              value={homeCountry}
              onChange={(e) => setHomeCountry(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-slate-200 text-sm rounded-xl p-3 focus:ring-2 focus:ring-brand-500 focus:outline-none cursor-pointer font-medium"
            >
              {Object.entries(countryTaxData).map(([key, data]) => (
                <option key={key} value={key}>
                  {data.flag} {data.name} (Tax: {(data.effTax * 100).toFixed(0)}%)
                </option>
              ))}
            </select>
          </div>

          {/* Target Country Selector */}
          <div className="space-y-2">
            <label className="block text-xs font-semibold text-slate-300">{t('salary.target')}</label>
            <select
              value={targetCountry}
              onChange={(e) => setTargetCountry(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 text-slate-200 text-sm rounded-xl p-3 focus:ring-2 focus:ring-brand-500 focus:outline-none cursor-pointer font-medium"
            >
              {Object.entries(countryTaxData).map(([key, data]) => (
                <option key={key} value={key}>
                  {data.flag} {data.name} (Tax: {(data.effTax * 100).toFixed(0)}%)
                </option>
              ))}
            </select>
          </div>

          {/* Buttons for Share / Embed */}
          <div className="pt-2 flex flex-col sm:flex-row gap-2">
            <button
              onClick={handleExportReport}
              className="flex-1 py-3 px-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition flex items-center justify-center space-x-2 cursor-pointer border border-slate-700"
            >
              <Download className="w-4 h-4 text-emerald-400" />
              <span>{t('salary.downloadReport')}</span>
            </button>
            <button
              onClick={() => setShowEmbed(!showEmbed)}
              className="py-3 px-4 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs transition flex items-center justify-center space-x-2 cursor-pointer border border-slate-700"
            >
              <Code className="w-4 h-4 text-brand-400" />
              <span>{t('salary.embed')}</span>
            </button>
          </div>

          {/* Embed Code Panel */}
          {showEmbed && (
            <div className="p-3.5 rounded-xl bg-slate-950 border border-slate-800 space-y-2">
              <span className="text-[10px] text-slate-400 font-semibold block">{t('salary.embedLabel')}</span>
              <textarea
                readOnly
                value={embedCode}
                onClick={(e) => e.target.select()}
                className="w-full h-20 bg-slate-900 border border-slate-800 rounded-lg p-2 text-[10px] font-mono text-slate-300 focus:outline-none cursor-pointer"
              />
              <span className="text-[9px] text-slate-500">{t('salary.embedNotice')}</span>
            </div>
          )}
        </div>

        {/* Results Card */}
        <div className="lg:col-span-7 space-y-6">
          
          <div className="glass-card p-6 sm:p-8 rounded-2xl border-brand-500/30 relative overflow-hidden bg-gradient-to-br from-slate-900 via-slate-900 to-slate-950">
            <div className="absolute -top-12 -right-12 w-40 h-40 bg-brand-500/10 rounded-full blur-3xl pointer-events-none"></div>

            <div className="flex items-center justify-between border-b border-slate-800 pb-4 mb-6">
              <div>
                <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">{t('salary.netHome')}</span>
                <h4 className="text-xl font-bold text-white flex items-center space-x-2 mt-1">
                  <span>{result.home.flag} vs {result.target.flag}</span>
                </h4>
              </div>
              <div className="text-right">
                <span className="text-xs font-medium text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/20">
                  {result.purchasingPowerBoost}x {t('salary.boost')}
                </span>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              
              {/* Home Country Net */}
              <div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800">
                <div className="text-xs text-slate-400 font-medium mb-1">{result.home.flag} {result.home.name}</div>
                <div className="text-2xl font-extrabold text-white font-mono">
                  ${Math.round(result.home.netMonthly).toLocaleString()}
                </div>
                <div className="text-[11px] text-slate-500 mt-1">
                  {t('salary.netMonthlyAfterTax').replace('{tax}', (result.home.effTax * 100).toFixed(0))}
                </div>
              </div>

              {/* Target Country Net */}
              <div className="p-4 rounded-xl bg-brand-950/40 border border-brand-500/30">
                <div className="text-xs text-brand-300 font-medium mb-1">{result.target.flag} {result.target.name}</div>
                <div className="text-2xl font-extrabold text-emerald-400 font-mono">
                  ${Math.round(result.target.netMonthly).toLocaleString()}
                </div>
                <div className="text-[11px] text-brand-300/70 mt-1">
                  {t('salary.netMonthlyAfterTax').replace('{tax}', (result.target.effTax * 100).toFixed(0))}
                </div>
              </div>

            </div>
          </div>

          {/* Recommendations */}
          <div className="glass-card p-6 rounded-2xl border-slate-800 space-y-4">
            <h4 className="text-xs font-bold text-white flex items-center space-x-2 uppercase tracking-wide">
              <Heart className="w-4 h-4 text-rose-500" />
              <span>{t('salary.recommendedNomad')}</span>
            </h4>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-xs">
              <a
                href="https://wise.prf.hn/click/camref:placeholder"
                target="_blank"
                rel="noopener noreferrer"
                className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="font-bold text-white">{t('salary.wise')}</div>
                  <p className="text-[10px] text-slate-400 mt-1">{t('salary.wiseDesc')}</p>
                </div>
                <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('salary.wiseCta')}</span>
              </a>

              <a
                href="https://safetywing.com?referralToken=placeholder"
                target="_blank"
                rel="noopener noreferrer"
                className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="font-bold text-white">{t('salary.safetyWing')}</div>
                  <p className="text-[10px] text-slate-400 mt-1">{t('salary.safetyWingDesc')}</p>
                </div>
                <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('salary.safetyWingCta')}</span>
              </a>

              <a
                href="https://revolut.ngru.net/placeholder"
                target="_blank"
                rel="noopener noreferrer"
                className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 hover:border-brand-500/40 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="font-bold text-white">{t('salary.revolut')}</div>
                  <p className="text-[10px] text-slate-400 mt-1">{t('salary.revolutDesc')}</p>
                </div>
                <span className="text-[10px] font-semibold text-brand-400 mt-2 block">{t('salary.revolutCta')}</span>
              </a>
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
